In [29]:
import pandas as pd
df = pd.read_csv("vlrscrape1.3.csv", parse_dates=["Date"])
df

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
0,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,Jinggg,-,1.37 1.33 1.39,323 314 332,...,9,6,3,4,1,3,5,5,0,Paper Rex
1,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,mindfreak,-,1.19 0.78 1.58,199 144 254,...,4,1,3,4,3,1,0,-2,2,Paper Rex
2,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,d4v41,-,1.12 1.23 1.02,175 174 177,...,5,2,3,2,1,1,3,1,2,Paper Rex
3,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,f0rsakeN,-,1.04 1.29 0.77,186 250 124,...,6,3,3,5,2,3,1,1,0,Paper Rex
4,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,cgrs,-,0.86 0.82 0.89,145 128 162,...,4,2,2,3,2,1,1,0,1,Paper Rex
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,d4v41,Kayo,1.05 0.83 1.22,154 141 165,...,1,0,1,1,1,0,0,-1,1,Paper Rex
476,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,f0rsakeN,Jett,0.97 1.26 0.76,262 318 221,...,4,3,1,4,1,3,0,2,-2,Paper Rex
477,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,Jinggg,Sage,0.91 0.99 0.85,183 153 206,...,3,1,2,3,0,3,0,1,-1,Paper Rex
478,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,mindfreak,Omen,0.87 1.02 0.76,171 198 151,...,1,1,0,2,1,1,-1,0,-1,Paper Rex
479,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,cgrs,Fade,0.65 0.60 0.69,166 166 166,...,1,1,0,1,0,1,0,1,-1,Paper Rex

In [30]:
df['Agent'] = df['Agent'].str.replace('-', 'Deadlock')
df

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
0,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,Jinggg,Deadlock,1.37 1.33 1.39,323 314 332,...,9,6,3,4,1,3,5,5,0,Paper Rex
1,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,mindfreak,Deadlock,1.19 0.78 1.58,199 144 254,...,4,1,3,4,3,1,0,-2,2,Paper Rex
2,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,d4v41,Deadlock,1.12 1.23 1.02,175 174 177,...,5,2,3,2,1,1,3,1,2,Paper Rex
3,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,f0rsakeN,Deadlock,1.04 1.29 0.77,186 250 124,...,6,3,3,5,2,3,1,1,0,Paper Rex
4,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,cgrs,Deadlock,0.86 0.82 0.89,145 128 162,...,4,2,2,3,2,1,1,0,1,Paper Rex
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,d4v41,Kayo,1.05 0.83 1.22,154 141 165,...,1,0,1,1,1,0,0,-1,1,Paper Rex
476,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,f0rsakeN,Jett,0.97 1.26 0.76,262 318 221,...,4,3,1,4,1,3,0,2,-2,Paper Rex
477,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,Jinggg,Sage,0.91 0.99 0.85,183 153 206,...,3,1,2,3,0,3,0,1,-1,Paper Rex
478,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,mindfreak,Omen,0.87 1.02 0.76,171 198 151,...,1,1,0,2,1,1,-1,0,-1,Paper Rex
479,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,cgrs,Fade,0.65 0.60 0.69,166 166 166,...,1,1,0,1,0,1,0,1,-1,Paper Rex

In [48]:
desired_rows = df[df.apply(lambda row: row.astype(str).str.contains('Paper Rex').any(), axis=1)]
desired_rows

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
0,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,Jinggg,Deadlock,1.37 1.33 1.39,323 314 332,...,9,6,3,4,1,3,5,5,0,Paper Rex
1,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,mindfreak,Deadlock,1.19 0.78 1.58,199 144 254,...,4,1,3,4,3,1,0,-2,2,Paper Rex
2,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,d4v41,Deadlock,1.12 1.23 1.02,175 174 177,...,5,2,3,2,1,1,3,1,2,Paper Rex
3,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,f0rsakeN,Deadlock,1.04 1.29 0.77,186 250 124,...,6,3,3,5,2,3,1,1,0,Paper Rex
4,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,cgrs,Deadlock,0.86 0.82 0.89,145 128 162,...,4,2,2,3,2,1,1,0,1,Paper Rex
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,d4v41,Kayo,1.05 0.83 1.22,154 141 165,...,1,0,1,1,1,0,0,-1,1,Paper Rex
476,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,f0rsakeN,Jett,0.97 1.26 0.76,262 318 221,...,4,3,1,4,1,3,0,2,-2,Paper Rex
477,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,Jinggg,Sage,0.91 0.99 0.85,183 153 206,...,3,1,2,3,0,3,0,1,-1,Paper Rex
478,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,mindfreak,Omen,0.87 1.02 0.76,171 198 151,...,1,1,0,2,1,1,-1,0,-1,Paper Rex
479,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,cgrs,Fade,0.65 0.60 0.69,166 166 166,...,1,1,0,1,0,1,0,1,-1,Paper Rex

In [49]:
teams = {}
for team in df['Team'].unique():
    teams[team] = {}

empty_df = pd.DataFrame()

for index, row in df.iterrows():
    column_value = row['Team']
    # Do something with the column value
    if teams[row['Team']].get(row['Player']) is None:
        teams[row['Team']][row['Player']] = {} 
        empty_df = pd.concat([empty_df, df[i:i+1]])

teams
# empty_df

{'Paper Rex': {'Jinggg ': {},
  'mindfreak ': {},
  'd4v41 ': {},
  'f0rsakeN ': {},
  'cgrs ': {}},
 'DRX': {'MaKo ': {}, 'Rb ': {}, 'Zest ': {}, 'BuZz ': {}, 'stax ': {}},
 'FNATIC': {'Alfajer ': {},
  'Chronicle ': {},
  'Leo ': {},
  'Derke ': {},
  'Boaster ': {}},
 'NRG Esports': {'s0m ': {},
  'crashies ': {},
  'Victor ': {},
  'FiNESSE ': {},
  'ardiis ': {}},
 'Team Liquid': {'Sayf ': {},
  'Redgar ': {},
  'soulcas ': {},
  'Jamppi ': {},
  'nAts ': {}},
 'EDward Gaming': {'ZmjjKK ': {},
  'CHICHOO ': {},
  'Smoggy ': {},
  'Haodong ': {},
  'nobody ': {}},
 'LOUD': {'aspas ': {},
  'tuyz ': {},
  'cauanzin ': {},
  'Less ': {},
  'saadhak ': {}},
 'Evil Geniuses': {'jawgemo ': {},
  'C0M ': {},
  'Demon1 ': {},
  'Ethan ': {},
  'Boostio ': {}}}

In [56]:
#Seperates  the databases of all players according to teams as the following JSON structure
'''
teams = {
    "team-name" : {
        'player-name' : {
            'compiled-stats': <DataFrame with averaged out stats>
            'allStats': <DataFrame more details>
        }
    }
}
'''

from IPython.display import display

for key in teams.keys():
    for player in teams[key].keys():
        teams[key][player]['compiledStats'] = df[df.apply(lambda row: row.astype(str).str.contains(player).any(), axis=1) & df.apply(lambda row: row.astype(str).str.contains('Deadlock').any(), axis=1)]
        teams[key][player]['allStats'] = df[df.apply(lambda row: row.astype(str).str.contains(player).any(), axis=1) & ~df.apply(lambda row: row.astype(str).str.contains('Deadlock').any(), axis=1)]

for key in teams.keys():
    for player in teams[key].keys():
        print(player)
        display(teams[key][player]['compiledStats'])

Jinggg

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
0,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,Jinggg,Deadlock,1.37 1.33 1.39,323 314 332,...,9,6,3,4,1,3,5,5,0,Paper Rex
130,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,All Maps,Jinggg,Deadlock,1.11 0.74 1.94,264 193 336,...,6,4,2,6,5,1,0,-1,1,Paper Rex
342,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,All Maps,Jinggg,Deadlock,0.96 0.69 1.21,273 232 309,...,9,3,6,10,8,2,-1,-5,4,Paper Rex
386,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,All Maps,Jinggg,Deadlock,1.01 1.11 0.94,225 235 216,...,10,4,6,10,5,5,0,-1,1,Paper Rex
427,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,All Maps,Jinggg,Deadlock,0.98 1.07 0.86,227 253 207,...,13,7,6,18,10,8,-5,-3,-2,Paper Rex

mindfreak

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
1,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,mindfreak,Deadlock,1.19 0.78 1.58,199 144 254,...,4,1,3,4,3,1,0,-2,2,Paper Rex
133,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,All Maps,mindfreak,Deadlock,0.73 0.62 1.08,133 91 185,...,2,1,1,1,0,1,1,1,0,Paper Rex
341,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,All Maps,mindfreak,Deadlock,1.06 1.06 1.05,186 190 187,...,7,1,6,5,2,3,2,-1,3,Paper Rex
389,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,All Maps,mindfreak,Deadlock,0.79 0.77 0.81,151 155 153,...,2,0,2,8,1,7,-6,-1,-5,Paper Rex
426,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,All Maps,mindfreak,Deadlock,0.98 0.92 1.09,189 176 213,...,5,1,4,9,6,3,-4,-5,1,Paper Rex

d4v41

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
2,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,d4v41,Deadlock,1.12 1.23 1.02,175 174 177,...,5,2,3,2,1,1,3,1,2,Paper Rex
132,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,All Maps,d4v41,Deadlock,0.75 0.54 1.14,147 129 168,...,3,1,2,3,1,2,0,0,0,Paper Rex
340,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,All Maps,d4v41,Deadlock,1.23 0.96 1.49,237 200 270,...,7,1,6,3,2,1,4,-1,5,Paper Rex
387,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,All Maps,d4v41,Deadlock,0.99 0.97 1.01,173 179 179,...,3,1,2,2,1,1,1,0,1,Paper Rex
425,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,All Maps,d4v41,Deadlock,1.07 1.02 1.10,190 198 182,...,8,3,5,6,4,2,2,-1,3,Paper Rex

f0rsakeN

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
3,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,f0rsakeN,Deadlock,1.04 1.29 0.77,186 250 124,...,6,3,3,5,2,3,1,1,0,Paper Rex
131,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,All Maps,f0rsakeN,Deadlock,0.97 0.90 1.17,204 192 223,...,4,1,3,3,2,1,1,-1,2,Paper Rex
344,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,All Maps,f0rsakeN,Deadlock,0.89 0.83 0.95,210 213 210,...,12,5,7,10,7,3,2,-2,4,Paper Rex
385,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,All Maps,f0rsakeN,Deadlock,1.08 1.02 1.14,239 216 266,...,16,9,7,12,8,4,4,1,3,Paper Rex
428,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,All Maps,f0rsakeN,Deadlock,0.91 0.78 1.12,220 201 240,...,17,9,8,21,12,9,-4,-3,-1,Paper Rex

cgrs

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
4,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,cgrs,Deadlock,0.86 0.82 0.89,145 128 162,...,4,2,2,3,2,1,1,0,1,Paper Rex
134,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,All Maps,cgrs,Deadlock,0.66 0.55 0.80,150 121 188,...,2,0,2,8,5,3,-6,-5,-1,Paper Rex
343,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,All Maps,cgrs,Deadlock,0.90 0.68 1.08,131 100 157,...,2,1,1,4,2,2,-2,-1,-1,Paper Rex
388,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,All Maps,cgrs,Deadlock,0.93 1.16 0.74,185 243 142,...,5,3,2,3,1,2,2,2,0,Paper Rex
429,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,All Maps,cgrs,Deadlock,0.71 0.60 0.82,143 123 165,...,2,1,1,10,5,5,-8,-4,-4,Paper Rex

MaKo

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
5,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,MaKo,Deadlock,1.08 1.26 0.92,218 276 160,...,1,1,0,5,2,3,-4,-1,-3,DRX

Rb

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
6,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,Rb,Deadlock,0.94 1.08 0.83,197 247 148,...,4,0,4,5,3,2,-1,-3,2,DRX

Zest

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
7,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,Zest,Deadlock,0.86 0.67 1.07,167 103 233,...,3,0,3,4,0,4,-1,0,-1,DRX

BuZz

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
8,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,BuZz,Deadlock,0.82 0.59 1.06,234 226 243,...,9,8,1,10,7,3,-1,1,-2,DRX

stax

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
9,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,stax,Deadlock,0.77 0.78 0.77,120 131 108,...,1,0,1,4,2,2,-3,-2,-1,DRX

Alfajer

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
30,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,All Maps,Alfajer,Deadlock,1.55 1.58 1.68,239 225 243,...,6,3,3,3,1,2,3,2,1,FNATIC
136,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,All Maps,Alfajer,Deadlock,1.28 0.70 1.60,220 147 288,...,3,0,3,4,3,1,-1,-3,2,FNATIC
192,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,All Maps,Alfajer,Deadlock,1.16 0.95 1.48,213 169 267,...,7,3,4,3,3,0,4,0,4,FNATIC
230,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,All Maps,Alfajer,Deadlock,1.31 1.18 1.48,246 254 235,...,7,3,4,2,2,0,5,1,4,FNATIC

Chronicle

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
31,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,All Maps,Chronicle,Deadlock,1.41 1.58 1.24,274 312 206,...,3,0,3,3,2,1,0,-2,2,FNATIC
137,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,All Maps,Chronicle,Deadlock,1.28 1.00 1.48,264 274 258,...,4,3,1,4,2,2,0,1,-1,FNATIC
191,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,All Maps,Chronicle,Deadlock,1.22 1.16 1.30,254 257 240,...,3,2,1,5,4,1,-2,-2,0,FNATIC
233,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,All Maps,Chronicle,Deadlock,1.02 0.88 1.19,177 138 223,...,5,1,4,7,5,2,-2,-4,2,FNATIC

Leo

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
32,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,All Maps,Leo,Deadlock,1.39 1.28 1.48,195 149 268,...,3,2,1,0,0,0,3,2,1,FNATIC
139,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,All Maps,Leo,Deadlock,0.99 0.86 0.97,166 177 155,...,3,2,1,0,0,0,3,2,1,FNATIC
190,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,All Maps,Leo,Deadlock,1.43 1.48 1.35,229 237 238,...,3,2,1,2,1,1,1,1,0,FNATIC
231,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,All Maps,Leo,Deadlock,1.29 1.24 1.36,200 208 183,...,2,0,2,0,0,0,2,0,2,FNATIC

Derke

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
33,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,All Maps,Derke,Deadlock,1.16 1.19 1.07,218 229 194,...,6,3,3,8,5,3,-2,-2,0,FNATIC
135,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,All Maps,Derke,Deadlock,1.39 0.91 1.56,293 259 317,...,9,3,6,6,4,2,3,-1,4,FNATIC
194,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,All Maps,Derke,Deadlock,0.94 0.83 1.27,217 193 221,...,20,13,7,11,4,7,9,9,0,FNATIC
232,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,All Maps,Derke,Deadlock,1.11 1.05 1.17,267 264 276,...,16,9,7,22,13,9,-6,-4,-2,FNATIC

Boaster

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
34,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,All Maps,Boaster,Deadlock,1.07 1.26 0.80,187 228 141,...,6,5,1,1,1,0,5,4,1,FNATIC
138,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,All Maps,Boaster,Deadlock,1.03 0.67 1.18,177 176 178,...,2,0,2,3,1,2,-1,-1,0,FNATIC
193,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,All Maps,Boaster,Deadlock,1.10 0.96 1.25,176 160 199,...,5,3,2,3,1,2,2,2,0,FNATIC
234,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,All Maps,Boaster,Deadlock,0.99 0.93 1.04,153 136 169,...,3,1,2,7,3,4,-4,-2,-2,FNATIC

s0m

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
35,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,All Maps,s0m,Deadlock,0.91 1.10 0.66,196 243 176,...,6,2,4,2,1,1,4,1,3,NRG Esports
306,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,All Maps,s0m,Deadlock,1.11 1.01 1.19,182 174 190,...,5,1,4,5,4,1,0,-3,3,NRG Esports
380,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,All Maps,s0m,Deadlock,1.24 1.11 1.38,248 197 304,...,7,2,5,6,4,2,1,-2,3,NRG Esports

crashies

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
36,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,All Maps,crashies,Deadlock,0.71 0.76 0.67,135 142 132,...,2,1,1,3,1,2,-1,0,-1,NRG Esports
307,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,All Maps,crashies,Deadlock,1.06 0.89 1.27,174 168 190,...,3,1,2,5,3,2,-2,-2,0,NRG Esports
384,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,All Maps,crashies,Deadlock,0.85 0.99 0.67,138 163 125,...,3,2,1,9,5,4,-6,-3,-3,NRG Esports

Victor

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
37,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,All Maps,Victor,Deadlock,0.66 1.02 0.44,177 210 148,...,3,1,2,10,5,5,-7,-4,-3,NRG Esports
305,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,All Maps,Victor,Deadlock,1.15 0.93 1.43,250 189 296,...,5,1,4,3,2,1,2,-1,3,NRG Esports
383,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,All Maps,Victor,Deadlock,1.02 0.97 1.09,191 169 201,...,6,3,3,8,4,4,-2,-1,-1,NRG Esports

FiNESSE

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
38,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,All Maps,FiNESSE,Deadlock,0.55 0.35 0.67,101 92 111,...,0,0,0,4,2,2,-4,-2,-2,NRG Esports
309,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,All Maps,FiNESSE,Deadlock,0.96 0.99 1.01,197 222 172,...,6,0,6,8,2,6,-2,-2,0,NRG Esports
381,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,All Maps,FiNESSE,Deadlock,1.14 1.38 0.80,233 262 195,...,9,6,3,3,0,3,6,6,0,NRG Esports

ardiis

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
39,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,All Maps,ardiis,Deadlock,0.52 0.42 0.58,132 141 137,...,4,2,2,5,2,3,-1,0,-1,NRG Esports
308,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,All Maps,ardiis,Deadlock,1.03 0.68 1.49,194 155 237,...,11,7,4,14,13,1,-3,-6,3,NRG Esports
382,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,All Maps,ardiis,Deadlock,1.07 1.04 1.10,214 226 196,...,10,6,4,10,6,4,0,0,0,NRG Esports

Sayf

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
60,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,All Maps,Sayf,Deadlock,1.27 1.40 1.13,292 337 257,...,15,7,8,13,7,6,2,0,2,Team Liquid
162,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,Sayf,Deadlock,0.70 0.34 0.92,196 127 247,...,4,2,2,7,6,1,-3,-4,1,Team Liquid
302,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,All Maps,Sayf,Deadlock,1.06 0.60 1.46,234 175 289,...,13,5,8,12,9,3,1,-4,5,Team Liquid

Redgar

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
61,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,All Maps,Redgar,Deadlock,1.03 1.03 1.00,169 163 176,...,4,0,4,7,2,5,-3,-2,-1,Team Liquid
163,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,Redgar,Deadlock,0.62 1.07 0.52,125 173 99,...,3,0,3,5,1,4,-2,-1,-1,Team Liquid
304,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,All Maps,Redgar,Deadlock,0.63 0.48 0.76,111 102 127,...,6,1,5,9,4,5,-3,-3,0,Team Liquid

soulcas

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
62,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,All Maps,soulcas,Deadlock,0.99 0.93 1.02,189 163 215,...,1,0,1,5,4,1,-4,-4,0,Team Liquid
164,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,soulcas,Deadlock,0.61 0.58 0.72,152 141 169,...,2,1,1,5,1,4,-3,0,-3,Team Liquid
300,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,All Maps,soulcas,Deadlock,1.12 0.83 1.25,182 178 183,...,4,2,2,3,2,1,1,0,1,Team Liquid

Jamppi

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
63,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,All Maps,Jamppi,Deadlock,0.90 0.94 0.86,175 193 160,...,2,1,1,11,4,7,-9,-3,-6,Team Liquid
161,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,Jamppi,Deadlock,0.92 1.30 0.73,192 234 164,...,2,0,2,3,1,2,-1,-1,0,Team Liquid
303,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,All Maps,Jamppi,Deadlock,0.88 0.71 1.01,171 145 200,...,5,0,5,5,4,1,0,-4,4,Team Liquid

nAts

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
64,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,All Maps,nAts,Deadlock,0.82 0.76 0.88,159 168 154,...,5,2,3,4,4,0,1,-2,3,Team Liquid
160,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,nAts,Deadlock,1.08 0.89 1.10,251 220 274,...,5,2,3,1,1,0,4,1,3,Team Liquid
301,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,All Maps,nAts,Deadlock,1.12 1.11 1.11,244 296 211,...,7,3,4,1,1,0,6,2,4,Team Liquid

ZmjjKK

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
65,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,All Maps,ZmjjKK,Deadlock,1.17 1.18 1.17,293 309 280,...,22,13,9,9,5,4,13,8,5,EDward Gaming
272,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,All Maps,ZmjjKK,Deadlock,1.13 1.19 1.08,265 282 241,...,9,6,3,9,5,4,0,1,-1,EDward Gaming
346,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,All Maps,ZmjjKK,Deadlock,1.00 0.67 1.34,246 195 310,...,14,6,8,12,8,4,2,-2,4,EDward Gaming

CHICHOO

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
66,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,All Maps,CHICHOO,Deadlock,0.98 1.04 0.90,174 175 171,...,3,2,1,1,1,0,2,1,1,EDward Gaming
271,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,All Maps,CHICHOO,Deadlock,1.15 1.22 1.11,178 181 180,...,1,0,1,1,1,0,0,-1,1,EDward Gaming
347,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,All Maps,CHICHOO,Deadlock,0.97 1.08 0.85,198 230 178,...,2,0,2,5,3,2,-3,-3,0,EDward Gaming

Smoggy

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
67,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,All Maps,Smoggy,Deadlock,0.97 0.87 1.09,154 121 194,...,6,2,4,7,7,0,-1,-5,4,EDward Gaming
274,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,All Maps,Smoggy,Deadlock,0.99 1.05 0.93,179 185 165,...,4,2,2,4,2,2,0,0,0,EDward Gaming
345,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,All Maps,Smoggy,Deadlock,1.12 0.91 1.36,214 193 233,...,6,1,5,2,2,0,4,-1,5,EDward Gaming

Haodong

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
68,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,All Maps,Haodong,Deadlock,0.94 0.91 1.00,165 164 167,...,4,1,3,5,1,4,-1,0,-1,EDward Gaming
273,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,All Maps,Haodong,Deadlock,1.07 1.33 0.78,200 215 188,...,3,2,1,3,2,1,0,0,0,EDward Gaming
348,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,All Maps,Haodong,Deadlock,0.95 0.76 1.16,193 169 215,...,8,3,5,10,8,2,-2,-5,3,EDward Gaming

nobody

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
69,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,All Maps,nobody,Deadlock,0.89 0.96 0.84,171 157 188,...,5,1,4,5,3,2,0,-2,2,EDward Gaming
270,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,All Maps,nobody,Deadlock,1.27 1.23 1.37,265 260 265,...,4,2,2,4,1,3,0,1,-1,EDward Gaming
349,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,All Maps,nobody,Deadlock,0.91 0.86 0.97,172 179 159,...,2,1,1,8,5,3,-6,-4,-2,EDward Gaming

aspas

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
100,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,aspas,Deadlock,0.89 0.95 0.94,231 213 256,...,7,2,5,5,5,0,2,-3,5,LOUD
275,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,All Maps,aspas,Deadlock,1.19 1.82 0.70,274 420 153,...,10,8,2,11,5,6,-1,3,-4,LOUD

tuyz

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
101,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,tuyz,Deadlock,0.88 0.95 0.68,194 220 157,...,3,1,2,2,2,0,1,-1,2,LOUD
277,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,All Maps,tuyz,Deadlock,0.79 0.73 0.78,133 127 139,...,3,0,3,0,0,0,3,0,3,LOUD

cauanzin

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
102,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,cauanzin,Deadlock,0.82 0.74 0.93,180 170 193,...,4,2,2,4,2,2,0,0,0,LOUD
279,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,All Maps,cauanzin,Deadlock,0.71 0.61 0.78,161 125 194,...,3,0,3,2,1,1,1,-1,2,LOUD

Less

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
103,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,Less,Deadlock,0.77 0.72 0.68,161 154 170,...,1,0,1,6,2,4,-5,-2,-3,LOUD
276,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,All Maps,Less,Deadlock,1.05 0.84 1.23,239 197 290,...,2,0,2,3,0,3,-1,0,-1,LOUD

saadhak

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
104,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,saadhak,Deadlock,0.55 0.64 0.42,122 140 102,...,1,1,0,5,3,2,-4,-2,-2,LOUD
278,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,All Maps,saadhak,Deadlock,0.74 0.67 0.73,138 125 148,...,3,2,1,5,3,2,-2,-1,-1,LOUD

jawgemo

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
105,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,jawgemo,Deadlock,1.55 1.64 1.62,293 275 309,...,6,4,2,5,3,2,1,1,0,Evil Geniuses
168,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,jawgemo,Deadlock,1.13 1.32 0.99,191 231 129,...,2,2,0,5,3,2,-3,-1,-2,Evil Geniuses
196,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,All Maps,jawgemo,Deadlock,0.88 0.62 1.00,208 210 209,...,9,5,4,13,8,5,-4,-3,-1,Evil Geniuses
239,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,All Maps,jawgemo,Deadlock,0.72 0.68 0.74,173 185 165,...,9,6,3,10,8,2,-1,-2,1,Evil Geniuses
422,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,All Maps,jawgemo,Deadlock,1.09 1.07 1.06,208 199 212,...,15,5,10,14,5,9,1,0,1,Evil Geniuses

C0M

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
106,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,C0M,Deadlock,1.42 1.62 1.31,204 224 189,...,1,0,1,2,1,1,-1,-1,0,Evil Geniuses
166,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,C0M,Deadlock,1.27 1.10 1.31,240 215 257,...,4,3,1,4,4,0,0,-1,1,Evil Geniuses
197,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,All Maps,C0M,Deadlock,0.81 0.80 0.79,136 173 119,...,1,1,0,6,2,4,-5,-1,-4,Evil Geniuses
238,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,All Maps,C0M,Deadlock,0.76 0.67 0.84,146 117 176,...,4,1,3,7,4,3,-3,-3,0,Evil Geniuses
421,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,All Maps,C0M,Deadlock,1.14 1.11 1.18,212 234 195,...,11,6,5,4,2,2,7,4,3,Evil Geniuses

Demon1

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
107,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,Demon1,Deadlock,1.30 1.36 1.21,242 250 237,...,5,1,4,6,3,3,-1,-2,1,Evil Geniuses
169,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,Demon1,Deadlock,0.94 0.97 0.85,164 190 123,...,3,0,3,3,2,1,0,-2,2,Evil Geniuses
198,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,All Maps,Demon1,Deadlock,0.80 0.60 0.92,170 169 179,...,4,1,3,8,2,6,-4,-1,-3,Evil Geniuses
236,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,All Maps,Demon1,Deadlock,0.98 0.96 0.98,199 228 180,...,12,5,7,4,2,2,8,3,5,Evil Geniuses
420,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,All Maps,Demon1,Deadlock,1.26 1.17 1.37,243 213 266,...,16,6,10,8,4,4,8,2,6,Evil Geniuses

Ethan

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
108,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,Ethan,Deadlock,1.15 1.22 1.05,250 274 222,...,3,0,3,1,1,0,2,-1,3,Evil Geniuses
167,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,Ethan,Deadlock,1.26 1.32 0.94,173 188 153,...,3,1,2,2,1,1,1,0,1,Evil Geniuses
199,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,All Maps,Ethan,Deadlock,0.79 0.70 0.90,163 172 174,...,3,2,1,2,2,0,1,0,1,Evil Geniuses
235,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,All Maps,Ethan,Deadlock,1.13 1.11 1.14,193 223 163,...,3,0,3,4,0,4,-1,0,-1,Evil Geniuses
423,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,All Maps,Ethan,Deadlock,1.06 0.98 1.14,172 166 179,...,5,2,3,3,3,0,2,-1,3,Evil Geniuses

Boostio

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
109,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,Boostio,Deadlock,0.73 0.58 0.85,156 167 145,...,7,3,4,2,2,0,5,1,4,Evil Geniuses
165,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,All Maps,Boostio,Deadlock,1.42 1.16 1.71,317 275 366,...,9,5,4,2,1,1,7,4,3,Evil Geniuses
195,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,All Maps,Boostio,Deadlock,0.91 0.57 1.10,197 150 237,...,7,2,5,9,1,8,-2,1,-3,Evil Geniuses
237,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,All Maps,Boostio,Deadlock,0.90 0.54 1.23,189 119 246,...,10,3,7,8,5,3,2,-2,4,Evil Geniuses
424,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,All Maps,Boostio,Deadlock,0.97 0.74 1.12,219 201 232,...,17,8,9,16,10,6,1,-2,3,Evil Geniuses

In [63]:
for key in teams.keys():
    for player in teams[key].keys():
        for index, row in teams[key][player]['compiledStats'].iterrows():
            print(row['R'])

1.37 1.33 1.39
1.11 0.74 1.94
0.96 0.69 1.21
1.01 1.11 0.94
0.98 1.07 0.86
1.19 0.78 1.58
0.73 0.62 1.08
1.06 1.06 1.05
0.79 0.77 0.81
0.98 0.92 1.09
1.12 1.23 1.02
0.75 0.54 1.14
1.23 0.96 1.49
0.99 0.97 1.01
1.07 1.02 1.10
1.04 1.29 0.77
0.97 0.90 1.17
0.89 0.83 0.95
1.08 1.02 1.14
0.91 0.78 1.12
0.86 0.82 0.89
0.66 0.55 0.80
0.90 0.68 1.08
0.93 1.16 0.74
0.71 0.60 0.82
1.08 1.26 0.92
0.94 1.08 0.83
0.86 0.67 1.07
0.82 0.59 1.06
0.77 0.78 0.77
1.55 1.58 1.68
1.28 0.70 1.60
1.16 0.95 1.48
1.31 1.18 1.48
1.41 1.58 1.24
1.28 1.00 1.48
1.22 1.16 1.30
1.02 0.88 1.19
1.39 1.28 1.48
0.99 0.86 0.97
1.43 1.48 1.35
1.29 1.24 1.36
1.16 1.19 1.07
1.39 0.91 1.56
0.94 0.83 1.27
1.11 1.05 1.17
1.07 1.26 0.80
1.03 0.67 1.18
1.10 0.96 1.25
0.99 0.93 1.04
0.91 1.10 0.66
1.11 1.01 1.19
1.24 1.11 1.38
0.71 0.76 0.67
1.06 0.89 1.27
0.85 0.99 0.67
0.66 1.02 0.44
1.15 0.93 1.43
1.02 0.97 1.09
0.55 0.35 0.67
0.96 0.99 1.01
1.14 1.38 0.80
0.52 0.42 0.58
1.03 0.68 1.49
1.07 1.04 1.10
1.27 1.40 1.13
0.70 0.34 0.92
1.06 0.60 1.46
1.03 1.03 1.00
0.62 1.07 0.52
0.63 0.48 0.76
0.99 0.93 1.02
0.61 0.58 0.72
1.12 0.83 1.25
0.90 0.94 0.86
0.92 1.30 0.73
0.88 0.71 1.01
0.82 0.76 0.88
1.08 0.89 1.10
1.12 1.11 1.11
1.17 1.18 1.17
1.13 1.19 1.08
1.00 0.67 1.34
0.98 1.04 0.90
1.15 1.22 1.11
0.97 1.08 0.85
0.97 0.87 1.09
0.99 1.05 0.93
1.12 0.91 1.36
0.94 0.91 1.00
1.07 1.33 0.78
0.95 0.76 1.16
0.89 0.96 0.84
1.27 1.23 1.37
0.91 0.86 0.97
0.89 0.95 0.94
1.19 1.82 0.70
0.88 0.95 0.68
0.79 0.73 0.78
0.82 0.74 0.93
0.71 0.61 0.78
0.77 0.72 0.68
1.05 0.84 1.23
0.55 0.64 0.42
0.74 0.67 0.73
1.55 1.64 1.62
1.13 1.32 0.99
0.88 0.62 1.00
0.72 0.68 0.74
1.09 1.07 1.06
1.42 1.62 1.31
1.27 1.10 1.31
0.81 0.80 0.79
0.76 0.67 0.84
1.14 1.11 1.18
1.30 1.36 1.21
0.94 0.97 0.85
0.80 0.60 0.92
0.98 0.96 0.98
1.26 1.17 1.37
1.15 1.22 1.05
1.26 1.32 0.94
0.79 0.70 0.90
1.13 1.11 1.14
1.06 0.98 1.14
0.73 0.58 0.85
1.42 1.16 1.71
0.91 0.57 1.10
0.90 0.54 1.23
0.97 0.74 1.12