In [29]:
import pandas as pd
df = pd.read_csv("vlrscrape1.3.csv", parse_dates=["Date"])
df

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
0,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,Jinggg,-,1.37 1.33 1.39,323 314 332,...,9,6,3,4,1,3,5,5,0,Paper Rex
1,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,mindfreak,-,1.19 0.78 1.58,199 144 254,...,4,1,3,4,3,1,0,-2,2,Paper Rex
2,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,d4v41,-,1.12 1.23 1.02,175 174 177,...,5,2,3,2,1,1,3,1,2,Paper Rex
3,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,f0rsakeN,-,1.04 1.29 0.77,186 250 124,...,6,3,3,5,2,3,1,1,0,Paper Rex
4,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,cgrs,-,0.86 0.82 0.89,145 128 162,...,4,2,2,3,2,1,1,0,1,Paper Rex
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,d4v41,Kayo,1.05 0.83 1.22,154 141 165,...,1,0,1,1,1,0,0,-1,1,Paper Rex
476,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,f0rsakeN,Jett,0.97 1.26 0.76,262 318 221,...,4,3,1,4,1,3,0,2,-2,Paper Rex
477,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,Jinggg,Sage,0.91 0.99 0.85,183 153 206,...,3,1,2,3,0,3,0,1,-1,Paper Rex
478,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,mindfreak,Omen,0.87 1.02 0.76,171 198 151,...,1,1,0,2,1,1,-1,0,-1,Paper Rex
479,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,cgrs,Fade,0.65 0.60 0.69,166 166 166,...,1,1,0,1,0,1,0,1,-1,Paper Rex

In [30]:
df['Agent'] = df['Agent'].str.replace('-', 'Deadlock')
df

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
0,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,Jinggg,Deadlock,1.37 1.33 1.39,323 314 332,...,9,6,3,4,1,3,5,5,0,Paper Rex
1,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,mindfreak,Deadlock,1.19 0.78 1.58,199 144 254,...,4,1,3,4,3,1,0,-2,2,Paper Rex
2,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,d4v41,Deadlock,1.12 1.23 1.02,175 174 177,...,5,2,3,2,1,1,3,1,2,Paper Rex
3,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,f0rsakeN,Deadlock,1.04 1.29 0.77,186 250 124,...,6,3,3,5,2,3,1,1,0,Paper Rex
4,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,cgrs,Deadlock,0.86 0.82 0.89,145 128 162,...,4,2,2,3,2,1,1,0,1,Paper Rex
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,d4v41,Kayo,1.05 0.83 1.22,154 141 165,...,1,0,1,1,1,0,0,-1,1,Paper Rex
476,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,f0rsakeN,Jett,0.97 1.26 0.76,262 318 221,...,4,3,1,4,1,3,0,2,-2,Paper Rex
477,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,Jinggg,Sage,0.91 0.99 0.85,183 153 206,...,3,1,2,3,0,3,0,1,-1,Paper Rex
478,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,mindfreak,Omen,0.87 1.02 0.76,171 198 151,...,1,1,0,2,1,1,-1,0,-1,Paper Rex
479,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,cgrs,Fade,0.65 0.60 0.69,166 166 166,...,1,1,0,1,0,1,0,1,-1,Paper Rex

In [48]:
desired_rows = df[df.apply(lambda row: row.astype(str).str.contains('Paper Rex').any(), axis=1)]
desired_rows

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
0,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,Jinggg,Deadlock,1.37 1.33 1.39,323 314 332,...,9,6,3,4,1,3,5,5,0,Paper Rex
1,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,mindfreak,Deadlock,1.19 0.78 1.58,199 144 254,...,4,1,3,4,3,1,0,-2,2,Paper Rex
2,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,d4v41,Deadlock,1.12 1.23 1.02,175 174 177,...,5,2,3,2,1,1,3,1,2,Paper Rex
3,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,f0rsakeN,Deadlock,1.04 1.29 0.77,186 250 124,...,6,3,3,5,2,3,1,1,0,Paper Rex
4,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,All Maps,cgrs,Deadlock,0.86 0.82 0.89,145 128 162,...,4,2,2,3,2,1,1,0,1,Paper Rex
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,d4v41,Kayo,1.05 0.83 1.22,154 141 165,...,1,0,1,1,1,0,0,-1,1,Paper Rex
476,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,f0rsakeN,Jett,0.97 1.26 0.76,262 318 221,...,4,3,1,4,1,3,0,2,-2,Paper Rex
477,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,Jinggg,Sage,0.91 0.99 0.85,183 153 206,...,3,1,2,3,0,3,0,1,-1,Paper Rex
478,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,mindfreak,Omen,0.87 1.02 0.76,171 198 151,...,1,1,0,2,1,1,-1,0,-1,Paper Rex
479,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,cgrs,Fade,0.65 0.60 0.69,166 166 166,...,1,1,0,1,0,1,0,1,-1,Paper Rex

In [49]:
teams = {}
for team in df['Team'].unique():
    teams[team] = {}

empty_df = pd.DataFrame()

for index, row in df.iterrows():
    column_value = row['Team']
    # Do something with the column value
    if teams[row['Team']].get(row['Player']) is None:
        teams[row['Team']][row['Player']] = {} 
        empty_df = pd.concat([empty_df, df[i:i+1]])

teams
# empty_df

{'Paper Rex': {'Jinggg ': {},
  'mindfreak ': {},
  'd4v41 ': {},
  'f0rsakeN ': {},
  'cgrs ': {}},
 'DRX': {'MaKo ': {}, 'Rb ': {}, 'Zest ': {}, 'BuZz ': {}, 'stax ': {}},
 'FNATIC': {'Alfajer ': {},
  'Chronicle ': {},
  'Leo ': {},
  'Derke ': {},
  'Boaster ': {}},
 'NRG Esports': {'s0m ': {},
  'crashies ': {},
  'Victor ': {},
  'FiNESSE ': {},
  'ardiis ': {}},
 'Team Liquid': {'Sayf ': {},
  'Redgar ': {},
  'soulcas ': {},
  'Jamppi ': {},
  'nAts ': {}},
 'EDward Gaming': {'ZmjjKK ': {},
  'CHICHOO ': {},
  'Smoggy ': {},
  'Haodong ': {},
  'nobody ': {}},
 'LOUD': {'aspas ': {},
  'tuyz ': {},
  'cauanzin ': {},
  'Less ': {},
  'saadhak ': {}},
 'Evil Geniuses': {'jawgemo ': {},
  'C0M ': {},
  'Demon1 ': {},
  'Ethan ': {},
  'Boostio ': {}}}

In [55]:
from IPython.display import display

for key in teams.keys():
    for player in teams[key].keys():
        teams[key][player]['compiledStats'] = df[df.apply(lambda row: row.astype(str).str.contains(player).any(), axis=1) & df.apply(lambda row: row.astype(str).str.contains('Deadlock').any(), axis=1)]
        teams[key][player]['allStats'] = df[df.apply(lambda row: row.astype(str).str.contains(player).any(), axis=1) & ~df.apply(lambda row: row.astype(str).str.contains('Deadlock').any(), axis=1)]

for key in teams.keys():
    for player in teams[key].keys():
        print(player)
        display(teams[key][player]['compiledStats'])

Jinggg

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
11,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,1 Split,Jinggg,Raze,1.28 1.46 1.10,318 338 297,...,7,5,2,1,0,1,6,5,1,Paper Rex
20,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,2 Bind,Jinggg,Raze,1.45 1.19 1.69,328 288 364,...,2,1,1,3,1,2,-1,0,-1,Paper Rex
140,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,1 Lotus,Jinggg,Raze,1.30 0.41 3.07,337 173 668,...,4,3,1,3,3,0,1,0,1,Paper Rex
151,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,2 Bind,Jinggg,Raze,0.92 1.07 0.81,191 222 170,...,2,1,1,3,2,1,-1,-1,0,Paper Rex
352,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,1 Fracture,Jinggg,Raze,1.07 0.58 1.56,284 219 351,...,3,1,2,6,4,2,-3,-3,0,Paper Rex
364,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,2 Split,Jinggg,Raze,0.57 0.40 0.72,189 115 252,...,3,0,3,3,3,0,0,-3,3,Paper Rex
370,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,3 Lotus,Jinggg,Raze,1.24 1.10 1.35,346 381 320,...,3,2,1,1,1,0,2,1,1,Paper Rex
397,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,1 Pearl,Jinggg,Phoenix,1.03 1.07 0.98,232 250 215,...,3,1,2,5,3,2,-2,-2,0,Paper Rex
405,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,2 Lotus,Jinggg,Raze,1.04 1.29 0.90,237 261 224,...,2,1,1,1,0,1,1,1,0,Paper Rex
418,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,3 Bind,Jinggg,Raze,0.96 0.97 0.94,205 201 210,...,5,2,3,4,2,2,1,0,1,Paper Rex
438,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,1 Fracture,Jinggg,Raze,0.75 0.75 0.75,217 224 208,...,3,1,2,4,3,1,-1,-2,1,Paper Rex
445,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,2 Lotus,Jinggg,Raze,1.35 1.54 1.15,319 391 248,...,3,3,0,2,2,0,1,1,0,Paper Rex
458,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,3 Split,Jinggg,Raze,0.95 0.76 1.15,203 182 228,...,3,1,2,6,3,3,-3,-2,-1,Paper Rex
466,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,4 Pearl,Jinggg,Phoenix,0.96 1.30 0.38,213 280 99,...,1,1,0,3,2,1,-2,-1,-1,Paper Rex
477,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,Jinggg,Sage,0.91 0.99 0.85,183 153 206,...,3,1,2,3,0,3,0,1,-1,Paper Rex

mindfreak

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
10,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,1 Split,mindfreak,Astra,1.34 1.24 1.45,216 217 216,...,3,1,2,0,0,0,3,1,2,Paper Rex
22,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,2 Bind,mindfreak,Brimstone,1.05 0.33 1.70,181 65 288,...,1,0,1,4,3,1,-3,-3,0,Paper Rex
143,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,1 Lotus,mindfreak,Omen,0.54 0.13 1.36,94 71 141,...,1,1,0,0,0,0,1,1,0,Paper Rex
152,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,2 Bind,mindfreak,Brimstone,0.92 1.11 0.79,172 120 207,...,1,0,1,1,0,1,0,0,0,Paper Rex
350,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,1 Fracture,mindfreak,Brimstone,1.30 1.17 1.43,227 247 209,...,3,1,2,1,1,0,2,0,2,Paper Rex
363,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,2 Split,mindfreak,Astra,0.64 0.87 0.45,134 150 122,...,0,0,0,0,0,0,0,0,0,Paper Rex
371,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,3 Lotus,mindfreak,Omen,1.23 1.16 1.28,196 154 229,...,4,0,4,4,1,3,0,-1,1,Paper Rex
399,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,1 Pearl,mindfreak,Astra,0.85 0.91 0.80,127 134 121,...,1,0,1,3,0,3,-2,0,-2,Paper Rex
409,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,2 Lotus,mindfreak,Omen,0.37 0.34 0.39,100 73 116,...,1,0,1,4,1,3,-3,-1,-2,Paper Rex
416,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,3 Bind,mindfreak,Brimstone,1.15 1.06 1.24,227 228 227,...,0,0,0,1,0,1,-1,0,-1,Paper Rex
435,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,1 Fracture,mindfreak,Brimstone,0.91 0.52 1.49,167 93 279,...,0,0,0,0,0,0,0,0,0,Paper Rex
446,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,2 Lotus,mindfreak,Omen,1.21 1.29 1.13,239 216 264,...,3,0,3,2,1,1,1,-1,2,Paper Rex
456,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,3 Split,mindfreak,Astra,1.23 1.07 1.40,225 222 230,...,1,0,1,3,2,1,-2,-2,0,Paper Rex
468,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,4 Pearl,mindfreak,Astra,0.70 0.72 0.65,143 154 125,...,0,0,0,2,2,0,-2,-2,0,Paper Rex
478,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,mindfreak,Omen,0.87 1.02 0.76,171 198 151,...,1,1,0,2,1,1,-1,0,-1,Paper Rex

d4v41

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
13,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,1 Split,d4v41,Viper,1.07 1.15 0.97,163 127 204,...,2,0,2,1,1,0,1,-1,2,Paper Rex
21,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,2 Bind,d4v41,Skye,1.18 1.31 1.06,187 226 152,...,3,2,1,1,0,1,2,2,0,Paper Rex
141,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,1 Lotus,d4v41,Skye,0.83 0.46 1.58,152 118 222,...,2,1,1,0,0,0,2,1,1,Paper Rex
154,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,2 Bind,d4v41,Skye,0.67 0.61 0.70,142 145 141,...,1,0,1,3,1,2,-2,-1,-1,Paper Rex
351,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,1 Fracture,d4v41,Killjoy,1.26 0.80 1.71,243 171 315,...,3,0,3,0,0,0,3,0,3,Paper Rex
360,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,2 Split,d4v41,Viper,1.29 0.88 1.63,234 160 295,...,1,0,1,1,1,0,0,-1,1,Paper Rex
373,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,3 Lotus,d4v41,Skye,1.16 1.20 1.12,234 285 196,...,3,1,2,2,1,1,1,0,1,Paper Rex
395,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,1 Pearl,d4v41,Skye,1.26 1.03 1.49,222 179 265,...,2,1,1,0,0,0,2,1,1,Paper Rex
408,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,2 Lotus,d4v41,Skye,0.64 0.56 0.69,130 173 105,...,0,0,0,0,0,0,0,0,0,Paper Rex
417,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,3 Bind,d4v41,Skye,1.08 1.32 0.84,168 184 152,...,1,0,1,2,1,1,-1,-1,0,Paper Rex
437,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,1 Fracture,d4v41,Killjoy,0.88 0.97 0.75,210 243 162,...,2,1,1,0,0,0,2,1,1,Paper Rex
447,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,2 Lotus,d4v41,Skye,1.13 1.14 1.12,176 167 186,...,4,1,3,3,2,1,1,-1,2,Paper Rex
455,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,3 Split,d4v41,Viper,1.34 1.21 1.47,226 240 211,...,0,0,0,1,0,1,-1,0,-1,Paper Rex
465,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,4 Pearl,d4v41,Skye,0.96 0.98 0.93,184 186 182,...,1,1,0,1,1,0,0,0,0,Paper Rex
475,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,d4v41,Kayo,1.05 0.83 1.22,154 141 165,...,1,0,1,1,1,0,0,-1,1,Paper Rex

f0rsakeN

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
12,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,1 Split,f0rsakeN,Jett,1.26 1.77 0.70,248 348 140,...,5,3,2,3,2,1,2,1,1,Paper Rex
24,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,2 Bind,f0rsakeN,Harbor,0.82 0.81 0.83,124 142 109,...,1,0,1,2,0,2,-1,0,-1,Paper Rex
142,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,1 Lotus,f0rsakeN,Cypher,0.80 0.58 1.24,149 161 125,...,0,0,0,2,2,0,-2,-2,0,Paper Rex
150,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,2 Bind,f0rsakeN,Harbor,1.15 1.23 1.09,258 238 272,...,4,1,3,1,0,1,3,1,2,Paper Rex
353,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,1 Fracture,f0rsakeN,Neon,0.89 0.82 0.97,223 232 215,...,5,3,2,3,2,1,2,1,1,Paper Rex
361,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,2 Split,f0rsakeN,Jett,0.86 0.88 0.83,228 253 208,...,6,2,4,4,2,2,2,0,2,Paper Rex
374,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,3 Lotus,f0rsakeN,Cypher,0.93 0.78 1.05,178 141 206,...,1,0,1,3,3,0,-2,-3,1,Paper Rex
398,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,1 Pearl,f0rsakeN,Jett,0.97 0.70 1.23,235 215 256,...,8,5,3,4,3,1,4,2,2,Paper Rex
406,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,2 Lotus,f0rsakeN,Cypher,0.77 0.78 0.76,196 159 218,...,5,2,3,5,3,2,0,-1,1,Paper Rex
415,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,3 Bind,f0rsakeN,Harbor,1.50 1.57 1.42,287 251 325,...,3,2,1,3,2,1,0,0,0,Paper Rex
436,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,1 Fracture,f0rsakeN,Neon,0.89 0.60 1.32,211 189 244,...,3,1,2,6,4,2,-3,-3,0,Paper Rex
448,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,2 Lotus,f0rsakeN,Cypher,0.91 1.08 0.74,187 213 163,...,3,2,1,2,0,2,1,2,-1,Paper Rex
457,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,3 Split,f0rsakeN,Jett,1.10 0.48 1.78,228 134 332,...,3,1,2,4,4,0,-1,-3,2,Paper Rex
469,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,4 Pearl,f0rsakeN,Jett,0.66 0.46 1.01,212 181 265,...,4,2,2,5,3,2,-1,-1,0,Paper Rex
476,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,f0rsakeN,Jett,0.97 1.26 0.76,262 318 221,...,4,3,1,4,1,3,0,2,-2,Paper Rex

cgrs

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
14,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,1 Split,cgrs,Skye,0.71 0.80 0.61,107 82 137,...,0,0,0,1,0,1,-1,0,-1,Paper Rex
23,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,2 Bind,cgrs,Gekko,1.01 0.84 1.17,182 179 185,...,4,2,2,2,2,0,2,0,2,Paper Rex
144,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,1 Lotus,cgrs,Gekko,0.40 0.29 0.62,104 95 124,...,1,0,1,5,2,3,-4,-2,-2,Paper Rex
153,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,2 Bind,cgrs,Gekko,0.91 0.80 0.99,195 160 219,...,1,0,1,3,3,0,-2,-3,1,Paper Rex
354,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,1 Fracture,cgrs,Breach,0.70 0.52 0.87,125 128 122,...,1,1,0,1,0,1,0,1,-1,Paper Rex
362,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,2 Split,cgrs,Skye,0.80 0.53 1.02,132 61 193,...,1,0,1,3,2,1,-2,-2,0,Paper Rex
372,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,3 Lotus,cgrs,Gekko,1.21 1.00 1.37,135 103 160,...,0,0,0,0,0,0,0,0,0,Paper Rex
396,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,1 Pearl,cgrs,Killjoy,1.17 1.28 1.06,241 264 219,...,1,0,1,1,1,0,0,-1,1,Paper Rex
407,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,2 Lotus,cgrs,Gekko,0.74 1.01 0.59,179 309 104,...,0,0,0,1,0,1,-1,0,-1,Paper Rex
419,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,3 Bind,cgrs,Gekko,0.88 1.18 0.57,136 181 91,...,4,3,1,1,0,1,3,3,0,Paper Rex
439,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,1 Fracture,cgrs,Breach,0.62 0.25 1.17,125 56 230,...,0,0,0,2,2,0,-2,-2,0,Paper Rex
449,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,2 Lotus,cgrs,Gekko,0.74 0.62 0.87,122 111 134,...,1,0,1,3,2,1,-2,-2,0,Paper Rex
459,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,3 Split,cgrs,Skye,0.84 0.54 1.17,148 109 192,...,0,0,0,2,1,1,-2,-1,-1,Paper Rex
467,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,4 Pearl,cgrs,Killjoy,0.71 1.00 0.21,153 183 102,...,0,0,0,2,0,2,-2,0,-2,Paper Rex
479,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,cgrs,Fade,0.65 0.60 0.69,166 166 166,...,1,1,0,1,0,1,0,1,-1,Paper Rex

MaKo

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
15,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,1 Split,MaKo,Viper,1.05 1.37 0.75,240 300 186,...,1,1,0,4,1,3,-3,0,-3,DRX
25,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,2 Bind,MaKo,Viper,1.12 1.14 1.09,195 254 132,...,0,0,0,1,1,0,-1,-1,0,DRX

Rb

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
16,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,1 Split,Rb,Neon,0.95 1.26 0.66,237 343 141,...,1,0,1,5,3,2,-4,-3,-1,DRX
26,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,2 Bind,Rb,Astra,0.94 0.90 0.99,157 159 156,...,3,0,3,0,0,0,3,0,3,DRX

Zest

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
18,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,1 Split,Zest,Astra,0.80 0.88 0.74,109 71 145,...,0,0,0,2,0,2,-2,0,-2,DRX
27,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,2 Bind,Zest,Fade,0.91 0.46 1.40,225 132 328,...,3,0,3,2,0,2,1,0,1,DRX

BuZz

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
17,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,1 Split,BuZz,Raze,0.85 0.69 0.99,237 239 237,...,3,2,1,5,3,2,-2,-1,-1,DRX
29,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,2 Bind,BuZz,Raze,0.79 0.48 1.13,230 213 249,...,6,6,0,5,4,1,1,2,-1,DRX

stax

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
19,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,1 Split,stax,Skye,0.72 0.92 0.54,128 147 111,...,1,0,1,1,1,0,0,-1,1,DRX
28,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,2 Bind,stax,Skye,0.82 0.65 1.00,111 116 106,...,0,0,0,3,1,2,-3,-1,-2,DRX

Alfajer

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
41,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,1 Fracture,Alfajer,Killjoy,1.31 1.56 1.10,193 198 189,...,3,1,2,2,0,2,1,1,0,FNATIC
50,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,2 Bind,Alfajer,Cypher,1.80 1.61 2.26,284 247 373,...,3,2,1,1,1,0,2,1,1,FNATIC
146,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,1 Lotus,Alfajer,Killjoy,1.28 0.19 1.83,210 77 278,...,1,0,1,2,1,1,-1,-1,0,FNATIC
156,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,2 Bind,Alfajer,Cypher,1.27 1.20 1.36,230 182 303,...,2,0,2,2,2,0,0,-2,2,FNATIC
202,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,1 Lotus,Alfajer,Killjoy,1.43 1.32 1.78,240 212 325,...,2,0,2,0,0,0,2,0,2,FNATIC
211,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,2 Fracture,Alfajer,Killjoy,1.04 0.53 1.67,196 131 274,...,3,2,1,3,3,0,0,-1,1,FNATIC
223,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,3 Split,Alfajer,Cypher,1.00 1.02 0.98,202 164 241,...,2,1,1,0,0,0,2,1,1,FNATIC
241,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,1 Lotus,Alfajer,Killjoy,1.49 1.12 1.99,285 252 331,...,2,0,2,1,1,0,1,-1,2,FNATIC
252,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,2 Split,Alfajer,Cypher,1.02 0.64 1.40,190 145 236,...,1,1,0,1,1,0,0,0,0,FNATIC
261,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,3 Bind,Alfajer,Cypher,1.41 1.77 1.05,262 357 167,...,4,2,2,0,0,0,4,2,2,FNATIC

Chronicle

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
42,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,1 Fracture,Chronicle,Breach,1.10 1.42 0.84,207 276 150,...,1,0,1,2,1,1,-1,-1,0,FNATIC
51,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,2 Bind,Chronicle,Viper,1.71 1.74 1.64,341 341 341,...,2,0,2,1,1,0,1,-1,2,FNATIC
147,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,1 Lotus,Chronicle,Viper,1.15 0.70 1.38,227 228 227,...,2,2,0,2,1,1,0,1,-1,FNATIC
155,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,2 Bind,Chronicle,Viper,1.41 1.29 1.59,300 297 305,...,2,1,1,2,1,1,0,0,0,FNATIC
200,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,1 Lotus,Chronicle,Viper,1.51 1.52 1.49,298 336 184,...,2,2,0,1,1,0,1,1,0,FNATIC
212,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,2 Fracture,Chronicle,Breach,0.99 0.68 1.36,230 187 283,...,0,0,0,1,1,0,-1,-1,0,FNATIC
221,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,3 Split,Chronicle,Breach,1.16 1.29 1.04,235 249 223,...,1,0,1,3,2,1,-2,-2,0,FNATIC
244,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,1 Lotus,Chronicle,Viper,0.78 0.55 1.08,128 107 157,...,0,0,0,3,3,0,-3,-3,0,FNATIC
251,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,2 Split,Chronicle,Breach,1.24 0.71 1.77,232 100 366,...,3,0,3,2,1,1,1,-1,2,FNATIC
263,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,3 Bind,Chronicle,Viper,1.05 1.37 0.73,170 204 137,...,2,1,1,2,1,1,0,0,0,FNATIC

Leo

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
40,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,1 Fracture,Leo,Fade,1.53 1.34 1.69,240 195 279,...,2,1,1,0,0,0,2,1,1,FNATIC
53,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,2 Bind,Leo,Skye,1.24 1.23 1.27,149 111 241,...,1,1,0,0,0,0,1,1,0,FNATIC
149,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,1 Lotus,Leo,Fade,1.06 0.66 1.26,181 198 172,...,2,1,1,0,0,0,2,1,1,FNATIC
159,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,2 Bind,Leo,Skye,0.91 1.06 0.68,151 166 129,...,1,1,0,0,0,0,1,1,0,FNATIC
203,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,1 Lotus,Leo,Fade,1.38 1.41 1.27,178 185 159,...,0,0,0,1,0,1,-1,0,-1,FNATIC
210,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,2 Fracture,Leo,Fade,1.13 1.29 0.95,183 232 126,...,0,0,0,1,1,0,-1,-1,0,FNATIC
220,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,3 Split,Leo,Skye,1.79 1.74 1.84,326 295 358,...,3,2,1,0,0,0,3,2,1,FNATIC
240,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,1 Lotus,Leo,Fade,1.54 1.35 1.79,269 267 273,...,0,0,0,0,0,0,0,0,0,FNATIC
250,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,2 Split,Leo,Skye,1.27 0.98 1.55,191 189 195,...,0,0,0,0,0,0,0,0,0,FNATIC
262,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,3 Bind,Leo,Skye,1.06 1.40 0.72,141 173 111,...,2,0,2,0,0,0,2,0,2,FNATIC

Derke

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
44,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,1 Fracture,Derke,Raze,0.79 0.75 0.82,180 170 190,...,4,1,3,4,3,1,0,-2,2,FNATIC
52,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,2 Bind,Derke,Raze,1.53 1.62 1.31,256 278 203,...,2,2,0,4,2,2,-2,0,-2,FNATIC
145,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,1 Lotus,Derke,Raze,1.71 0.64 2.25,369 273 418,...,4,0,4,3,1,2,1,-1,2,FNATIC
157,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,2 Bind,Derke,Raze,1.06 1.19 0.87,217 252 166,...,5,3,2,3,3,0,2,0,2,FNATIC
201,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,1 Lotus,Derke,Raze,1.50 1.20 2.42,323 250 541,...,7,6,1,1,1,0,6,5,1,FNATIC
214,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,2 Fracture,Derke,Raze,0.79 0.56 1.06,186 148 232,...,7,3,4,5,1,4,2,2,0,FNATIC
224,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,3 Split,Derke,Raze,0.54 0.74 0.33,141 179 104,...,6,4,2,5,2,3,1,2,-1,FNATIC
243,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,1 Lotus,Derke,Raze,0.95 0.83 1.10,230 254 199,...,5,3,2,6,4,2,-1,-1,0,FNATIC
253,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,2 Split,Derke,Raze,0.94 1.15 0.74,268 299 238,...,6,3,3,8,5,3,-2,-2,0,FNATIC
260,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,3 Bind,Derke,Raze,1.43 1.17 1.69,303 241 365,...,5,3,2,8,4,4,-3,-1,-2,FNATIC

Boaster

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
43,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,1 Fracture,Boaster,Brimstone,0.97 1.19 0.78,211 264 167,...,4,3,1,0,0,0,4,3,1,FNATIC
54,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,2 Bind,Boaster,Brimstone,1.18 1.34 0.81,162 198 78,...,2,2,0,1,1,0,1,1,0,FNATIC
148,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,1 Lotus,Boaster,Astra,1.09 0.34 1.46,180 115 214,...,1,0,1,1,0,1,0,0,0,FNATIC
158,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,2 Bind,Boaster,Brimstone,0.97 1.01 0.90,173 207 124,...,1,0,1,2,1,1,-1,-1,0,FNATIC
204,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,1 Lotus,Boaster,Astra,1.22 1.23 1.17,175 198 106,...,2,2,0,0,0,0,2,2,0,FNATIC
213,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,2 Fracture,Boaster,Brimstone,0.94 0.70 1.22,164 123 214,...,0,0,0,2,1,1,-2,-1,-1,FNATIC
222,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,3 Split,Boaster,Omen,1.15 0.95 1.36,188 159 217,...,3,1,2,1,0,1,2,1,1,FNATIC
242,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,1 Lotus,Boaster,Astra,1.09 1.08 1.11,183 177 192,...,2,0,2,2,1,1,0,-1,1,FNATIC
254,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,2 Split,Boaster,Omen,0.91 0.96 0.87,137 163 112,...,0,0,0,3,1,2,-3,-1,-2,FNATIC
264,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,3 Bind,Boaster,Brimstone,0.95 0.77 1.14,140 74 206,...,1,1,0,2,1,1,-1,0,-1,FNATIC

s0m

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
45,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,1 Fracture,s0m,Brimstone,1.23 1.65 0.73,266 305 220,...,3,2,1,1,0,1,2,2,0,NRG Esports
56,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,2 Bind,s0m,Harbor,0.58 0.55 0.59,125 94 139,...,3,0,3,1,1,0,2,-1,3,NRG Esports
318,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,1 Haven,s0m,Harbor,0.98 0.87 1.10,170 155 185,...,3,1,2,3,2,1,0,-1,1,NRG Esports
327,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,2 Ascent,s0m,Omen,0.97 0.80 1.10,195 160 222,...,2,0,2,1,1,0,1,-1,2,NRG Esports
336,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,3 Split,s0m,Astra,1.37 1.37 1.36,182 206 135,...,0,0,0,1,1,0,-1,-1,0,NRG Esports
390,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,1 Pearl,s0m,Harbor,1.22 0.91 1.53,231 158 304,...,2,1,1,5,3,2,-3,-2,-1,NRG Esports
400,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,2 Lotus,s0m,Omen,1.39 1.31 1.52,262 215 344,...,3,1,2,1,1,0,2,0,2,NRG Esports
410,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,3 Bind,s0m,Brimstone,1.10 1.11 1.10,252 225 280,...,2,0,2,0,0,0,2,0,2,NRG Esports

crashies

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
48,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,1 Fracture,crashies,Sova,0.78 0.83 0.73,141 143 140,...,1,1,0,3,1,2,-2,0,-2,NRG Esports
55,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,2 Bind,crashies,Skye,0.64 0.70 0.61,129 138 126,...,1,0,1,0,0,0,1,0,1,NRG Esports
315,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,1 Haven,crashies,Skye,1.26 0.89 1.63,190 153 229,...,1,0,1,3,2,1,-2,-2,0,NRG Esports
328,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,2 Ascent,crashies,Sova,0.89 0.85 0.93,215 249 190,...,1,1,0,0,0,0,1,1,0,NRG Esports
339,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,3 Split,crashies,Skye,1.04 0.94 1.24,117 123 107,...,1,0,1,2,1,1,-1,-1,0,NRG Esports
394,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,1 Pearl,crashies,Skye,0.72 0.61 0.82,174 155 194,...,1,0,1,2,1,1,-1,-1,0,NRG Esports
404,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,2 Lotus,crashies,Skye,0.93 1.05 0.72,70 67 76,...,0,0,0,2,2,0,-2,-2,0,NRG Esports
413,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,3 Bind,crashies,Skye,0.90 1.33 0.47,170 267 73,...,2,2,0,5,2,3,-3,0,-3,NRG Esports

Victor

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
47,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,1 Fracture,Victor,Raze,0.79 0.97 0.58,159 189 125,...,1,0,1,5,4,1,-4,-4,0,NRG Esports
57,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,2 Bind,Victor,Raze,0.52 1.06 0.29,194 260 167,...,2,1,1,5,1,4,-3,0,-3,NRG Esports
319,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,1 Haven,Victor,Killjoy,0.74 0.58 0.90,171 124 219,...,1,0,1,1,1,0,0,-1,1,NRG Esports
325,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,2 Ascent,Victor,Kayo,1.05 0.77 1.27,233 118 320,...,1,0,1,1,0,1,0,0,0,NRG Esports
335,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,3 Split,Victor,Raze,1.67 1.43 2.14,346 311 417,...,3,1,2,1,1,0,2,0,2,NRG Esports
393,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,1 Pearl,Victor,Killjoy,0.78 0.78 0.78,141 111 172,...,1,0,1,3,1,2,-2,-1,-1,NRG Esports
403,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,2 Lotus,Victor,Raze,1.29 1.20 1.46,262 219 339,...,3,2,1,2,1,1,1,1,0,NRG Esports
411,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,3 Bind,Victor,Raze,0.99 0.95 1.03,171 188 155,...,2,1,1,3,2,1,-1,-1,0,NRG Esports

FiNESSE

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
49,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,1 Fracture,FiNESSE,Breach,0.60 0.53 0.68,109 82 143,...,0,0,0,1,1,0,-1,-1,0,NRG Esports
58,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,2 Bind,FiNESSE,Viper,0.51 0.17 0.65,93 117 84,...,0,0,0,3,1,2,-3,-1,-2,NRG Esports
317,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,1 Haven,FiNESSE,Viper,0.99 1.13 0.85,225 259 191,...,3,0,3,3,1,2,0,-1,1,NRG Esports
329,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,2 Ascent,FiNESSE,Killjoy,0.56 0.70 0.46,143 203 99,...,2,0,2,5,1,4,-3,-1,-2,NRG Esports
337,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,3 Split,FiNESSE,Viper,1.33 1.14 1.71,223 198 275,...,1,0,1,0,0,0,1,0,1,NRG Esports
391,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,1 Pearl,FiNESSE,Viper,1.19 1.50 0.87,236 273 199,...,4,2,2,0,0,0,4,2,2,NRG Esports
401,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,2 Lotus,FiNESSE,Viper,1.38 1.83 0.62,276 360 134,...,3,3,0,2,0,2,1,3,-2,NRG Esports
414,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,3 Bind,FiNESSE,Viper,0.86 0.80 0.92,188 151 225,...,2,1,1,1,0,1,1,1,0,NRG Esports

ardiis

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
46,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,1 Fracture,ardiis,Killjoy,0.83 0.80 0.86,180 171 191,...,3,1,2,4,2,2,-1,-1,0,NRG Esports
59,2023-06-16 23:00:00,FNATIC NRG Esports,FNATIC,2:0,BO3,2 Bind,ardiis,Sage,0.21 0.04 0.30,84 70 91,...,1,1,0,1,0,1,0,1,-1,NRG Esports
316,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,1 Haven,ardiis,Jett,1.00 0.39 1.61,182 82 284,...,1,0,1,7,6,1,-6,-6,0,NRG Esports
326,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,2 Ascent,ardiis,Jett,0.97 0.88 1.04,200 247 166,...,6,4,2,2,2,0,4,2,2,NRG Esports
338,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,3 Split,ardiis,Jett,1.13 0.79 1.82,201 165 276,...,4,3,1,5,5,0,-1,-2,1,NRG Esports
392,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,1 Pearl,ardiis,Jett,0.97 0.85 1.09,215 200 232,...,5,3,2,5,3,2,0,0,0,NRG Esports
402,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,2 Lotus,ardiis,Killjoy,1.34 1.39 1.26,256 254 262,...,2,1,1,1,1,0,1,0,1,NRG Esports
412,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,3 Bind,ardiis,Chamber,0.91 0.88 0.94,172 230 115,...,3,2,1,4,2,2,-1,0,-1,NRG Esports

Sayf

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
70,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,1 Haven,Sayf,Jett,1.51 1.61 1.43,349 355 346,...,8,4,4,4,1,3,4,3,1,Team Liquid
82,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,2 Split,Sayf,Jett,0.89 0.71 1.03,230 204 251,...,4,1,3,6,4,2,-2,-3,1,Team Liquid
90,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,3 Lotus,Sayf,Raze,1.40 1.88 0.92,296 420 173,...,3,2,1,3,2,1,0,0,0,Team Liquid
172,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,Sayf,Raze,0.50 0.05 0.61,188 68 219,...,1,0,1,2,1,1,-1,-1,0,Team Liquid
183,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,2 Haven,Sayf,Jett,0.91 0.64 1.23,204 141 281,...,3,2,1,5,5,0,-2,-3,1,Team Liquid
311,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,1 Haven,Sayf,Jett,1.18 0.91 1.45,214 209 221,...,5,2,3,6,5,1,-1,-3,2,Team Liquid
322,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,2 Ascent,Sayf,Jett,1.19 0.76 1.76,289 183 432,...,3,2,1,2,2,0,1,0,1,Team Liquid
331,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,3 Split,Sayf,Jett,0.82 0.13 1.17,198 82 257,...,5,1,4,4,2,2,1,-1,2,Team Liquid

Redgar

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
72,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,1 Haven,Redgar,Omen,1.10 1.10 1.10,153 135 169,...,0,0,0,3,2,1,-3,-2,-1,Team Liquid
80,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,2 Split,Redgar,Omen,0.94 0.62 1.18,164 130 191,...,2,0,2,1,0,1,1,0,1,Team Liquid
92,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,3 Lotus,Redgar,Omen,1.04 1.38 0.70,190 212 169,...,2,0,2,3,0,3,-1,0,-1,Team Liquid
173,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,Redgar,Omen,0.46 1.37 0.23,106 257 69,...,1,0,1,2,0,2,-1,0,-1,Team Liquid
184,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,2 Haven,Redgar,Omen,0.79 0.77 0.81,144 152 136,...,2,0,2,3,1,2,-1,-1,0,Team Liquid
314,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,1 Haven,Redgar,Omen,0.73 0.60 0.86,137 151 124,...,2,0,2,1,1,0,1,-1,2,Team Liquid
324,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,2 Ascent,Redgar,Omen,0.64 0.55 0.77,130 83 193,...,4,1,3,5,2,3,-1,-1,0,Team Liquid
334,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,3 Split,Redgar,Omen,0.53 0.30 0.64,65 33 81,...,0,0,0,3,1,2,-3,-1,-2,Team Liquid

soulcas

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
71,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,1 Haven,soulcas,Skye,1.12 1.29 0.98,190 212 172,...,0,0,0,2,1,1,-2,-1,-1,Team Liquid
84,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,2 Split,soulcas,Sage,0.59 0.22 0.86,152 86 202,...,0,0,0,2,2,0,-2,-2,0,Team Liquid
91,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,3 Lotus,soulcas,Fade,1.25 1.27 1.24,224 179 270,...,1,0,1,1,1,0,0,-1,1,Team Liquid
174,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,soulcas,Viper,0.27 0.42 0.24,123 168 113,...,2,1,1,4,0,4,-2,1,-3,Team Liquid
181,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,2 Haven,soulcas,Skye,0.95 0.75 1.21,180 134 238,...,0,0,0,1,1,0,-1,-1,0,Team Liquid
312,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,1 Haven,soulcas,Skye,1.03 1.01 1.05,168 186 151,...,2,1,1,1,1,0,1,0,1,Team Liquid
320,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,2 Ascent,soulcas,Kayo,1.35 1.41 1.27,196 250 125,...,1,1,0,2,1,1,-1,0,-1,Team Liquid
330,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,3 Split,soulcas,Sage,0.97 0.06 1.42,181 18 262,...,1,0,1,0,0,0,1,0,1,Team Liquid

Jamppi

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
73,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,1 Haven,Jamppi,Breach,1.03 1.17 0.92,162 204 128,...,0,0,0,2,1,1,-2,-1,-1,Team Liquid
81,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,2 Split,Jamppi,Skye,0.92 0.90 0.94,204 197 211,...,1,0,1,2,0,2,-1,0,-1,Team Liquid
93,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,3 Lotus,Jamppi,Killjoy,0.73 0.74 0.73,159 179 141,...,1,1,0,7,3,4,-6,-2,-4,Team Liquid
171,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,Jamppi,Skye,0.91 1.48 0.77,193 304 166,...,1,0,1,1,0,1,0,0,0,Team Liquid
182,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,2 Haven,Jamppi,Breach,0.93 1.12 0.70,191 217 162,...,1,0,1,2,1,1,-1,-1,0,Team Liquid
313,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,1 Haven,Jamppi,Breach,0.94 0.64 1.23,198 107 289,...,3,0,3,1,1,0,2,-1,3,Team Liquid
323,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,2 Ascent,Jamppi,Sova,1.15 1.14 1.15,160 173 143,...,0,0,0,2,1,1,-2,-1,-1,Team Liquid
333,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,3 Split,Jamppi,Skye,0.54 0.35 0.64,154 170 147,...,2,0,2,2,2,0,0,-2,2,Team Liquid

nAts

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
74,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,1 Haven,nAts,Killjoy,0.94 0.76 1.10,193 184 201,...,2,0,2,1,1,0,1,-1,2,Team Liquid
83,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,2 Split,nAts,Cypher,0.83 0.92 0.77,129 155 110,...,2,1,1,1,1,0,1,0,1,Team Liquid
94,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,3 Lotus,nAts,Viper,0.70 0.61 0.78,156 163 151,...,1,1,0,2,2,0,-1,-1,0,Team Liquid
170,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,nAts,Cypher,0.93 0.49 1.04,245 203 257,...,1,1,0,0,0,0,1,1,0,Team Liquid
180,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,2 Haven,nAts,Killjoy,1.23 1.29 1.16,256 224 295,...,4,1,3,1,1,0,3,0,3,Team Liquid
310,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,1 Haven,nAts,Killjoy,1.26 0.95 1.58,287 282 292,...,5,2,3,0,0,0,5,2,3,Team Liquid
321,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,2 Ascent,nAts,Cypher,1.34 1.57 1.04,292 345 221,...,1,1,0,1,1,0,0,0,0,Team Liquid
332,2023-06-19 23:00:00,Team Liquid NRG Esports,NRG Esports,2:1,BO3,3 Split,nAts,Cypher,0.75 0.80 0.72,152 226 116,...,1,0,1,0,0,0,1,0,1,Team Liquid

ZmjjKK

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
76,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,1 Haven,ZmjjKK,Jett,0.90 0.94 0.86,226 252 195,...,4,2,2,5,3,2,-1,-1,0,EDward Gaming
86,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,2 Split,ZmjjKK,Raze,1.27 1.16 1.43,296 279 321,...,6,3,3,3,1,2,3,2,1,EDward Gaming
95,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,3 Lotus,ZmjjKK,Jett,1.33 1.44 1.21,358 396 321,...,12,8,4,1,1,0,11,7,4,EDward Gaming
282,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,1 Lotus,ZmjjKK,Jett,1.17 1.17 1.19,280 301 245,...,4,3,1,5,3,2,-1,0,-1,EDward Gaming
292,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,2 Fracture,ZmjjKK,Jett,1.08 1.21 0.96,249 262 238,...,5,3,2,4,2,2,1,1,0,EDward Gaming
356,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,1 Fracture,ZmjjKK,Jett,1.14 0.47 1.82,280 185 377,...,5,3,2,4,3,1,1,0,1,EDward Gaming
369,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,2 Split,ZmjjKK,Raze,0.97 0.73 1.26,222 172 283,...,3,1,2,4,4,0,-1,-3,2,EDward Gaming
378,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,3 Lotus,ZmjjKK,Jett,0.87 0.82 0.95,235 229 244,...,6,2,4,4,1,3,2,1,1,EDward Gaming

CHICHOO

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
77,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,1 Haven,CHICHOO,Cypher,0.79 0.75 0.84,179 143 223,...,1,1,0,0,0,0,1,1,0,EDward Gaming
85,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,2 Split,CHICHOO,Viper,1.33 1.42 1.22,205 241 158,...,2,1,1,0,0,0,2,1,1,EDward Gaming
99,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,3 Lotus,CHICHOO,Cypher,0.80 0.96 0.65,139 141 138,...,0,0,0,1,1,0,-1,-1,0,EDward Gaming
283,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,1 Lotus,CHICHOO,Cypher,1.07 1.04 1.13,149 115 208,...,1,0,1,1,1,0,0,-1,1,EDward Gaming
290,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,2 Fracture,CHICHOO,Killjoy,1.24 1.40 1.09,206 254 163,...,0,0,0,0,0,0,0,0,0,EDward Gaming
355,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,1 Fracture,CHICHOO,Killjoy,1.20 1.38 1.03,301 356 247,...,2,0,2,4,2,2,-2,-2,0,EDward Gaming
367,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,2 Split,CHICHOO,Viper,1.04 1.21 0.84,167 206 121,...,0,0,0,0,0,0,0,0,0,EDward Gaming
379,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,3 Lotus,CHICHOO,Cypher,0.66 0.65 0.68,127 117 142,...,0,0,0,1,1,0,-1,-1,0,EDward Gaming

Smoggy

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
79,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,1 Haven,Smoggy,Breach,0.77 0.63 0.93,127 81 183,...,2,1,1,2,2,0,0,-1,1,EDward Gaming
87,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,2 Split,Smoggy,Jett,1.17 1.10 1.27,171 165 180,...,3,1,2,4,4,0,-1,-3,2,EDward Gaming
96,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,3 Lotus,Smoggy,Raze,0.98 0.87 1.08,165 117 215,...,1,0,1,1,1,0,0,-1,1,EDward Gaming
281,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,1 Lotus,Smoggy,Raze,1.17 1.18 1.17,216 240 176,...,3,2,1,3,2,1,0,0,0,EDward Gaming
294,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,2 Fracture,Smoggy,Breach,0.81 0.93 0.69,142 124 159,...,1,0,1,1,0,1,0,0,0,EDward Gaming
357,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,1 Fracture,Smoggy,Breach,1.12 0.72 1.52,168 122 215,...,1,0,1,0,0,0,1,0,1,EDward Gaming
366,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,2 Split,Smoggy,Jett,1.33 1.30 1.38,255 280 225,...,3,0,3,1,1,0,2,-1,3,EDward Gaming
376,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,3 Lotus,Smoggy,Raze,0.91 0.71 1.17,218 183 267,...,2,1,1,1,1,0,1,0,1,EDward Gaming

Haodong

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
75,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,1 Haven,Haodong,Omen,0.96 1.00 0.92,205 224 184,...,3,1,2,1,0,1,2,1,1,EDward Gaming
89,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,2 Split,Haodong,Astra,0.98 0.62 1.45,142 88 215,...,0,0,0,1,1,0,-1,-1,0,EDward Gaming
97,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,3 Lotus,Haodong,Omen,0.88 1.12 0.64,148 180 116,...,1,0,1,3,0,3,-2,0,-2,EDward Gaming
284,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,1 Lotus,Haodong,Omen,1.02 1.13 0.82,175 191 150,...,0,0,0,2,1,1,-2,-1,-1,EDward Gaming
291,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,2 Fracture,Haodong,Brimstone,1.12 1.53 0.74,225 242 211,...,3,2,1,1,1,0,2,1,1,EDward Gaming
359,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,1 Fracture,Haodong,Brimstone,0.62 0.15 1.08,139 57 222,...,3,1,2,4,3,1,-1,-2,1,EDward Gaming
365,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,2 Split,Haodong,Astra,1.37 1.35 1.40,266 290 238,...,4,2,2,3,2,1,1,0,1,EDward Gaming
377,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,3 Lotus,Haodong,Omen,0.88 0.77 1.02,173 171 177,...,1,0,1,3,3,0,-2,-3,1,EDward Gaming

nobody

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
78,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,1 Haven,nobody,Sova,0.79 1.01 0.52,126 125 128,...,2,1,1,2,1,1,0,0,0,EDward Gaming
88,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,2 Split,nobody,Skye,1.07 0.75 1.51,194 133 278,...,1,0,1,1,1,0,0,-1,1,EDward Gaming
98,2023-06-16 01:30:00,Team Liquid EDward Gaming,Team Liquid,2:1,BO3,3 Lotus,nobody,Skye,0.81 1.11 0.51,193 215 171,...,2,0,2,2,1,1,0,-1,1,EDward Gaming
280,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,1 Lotus,nobody,Skye,1.52 1.39 1.75,302 283 336,...,0,0,0,0,0,0,0,0,0,EDward Gaming
293,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,2 Fracture,nobody,Skye,1.02 1.06 0.99,228 234 223,...,4,2,2,4,1,3,0,1,-1,EDward Gaming
358,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,1 Fracture,nobody,Skye,0.64 0.75 0.53,142 171 114,...,0,0,0,3,1,2,-3,-1,-2,EDward Gaming
368,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,2 Split,nobody,Skye,1.02 0.59 1.52,147 87 221,...,1,0,1,3,2,1,-2,-2,0,EDward Gaming
375,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,3 Lotus,nobody,Skye,1.06 1.22 0.85,226 279 156,...,1,1,0,2,2,0,-1,-1,0,EDward Gaming

aspas

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
110,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,aspas,Neon,1.15 1.37 1.00,277 305 259,...,4,1,3,2,2,0,2,-1,3,LOUD
122,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,2 Ascent,aspas,Jett,0.64 0.52 0.89,184 152 248,...,3,1,2,3,3,0,0,-2,2,LOUD
285,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,1 Lotus,aspas,Neon,1.08 1.83 0.65,276 519 136,...,3,3,0,2,0,2,1,3,-2,LOUD
296,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,2 Fracture,aspas,Neon,1.30 1.81 0.76,271 363 172,...,7,5,2,9,5,4,-2,0,-2,LOUD

tuyz

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
113,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,tuyz,Omen,0.68 0.56 0.76,120 83 145,...,1,0,1,0,0,0,1,0,1,LOUD
120,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,2 Ascent,tuyz,Omen,1.08 1.33 0.59,268 312 181,...,2,1,1,2,2,0,0,-1,1,LOUD
287,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,1 Lotus,tuyz,Omen,0.78 0.50 0.95,134 48 185,...,3,0,3,0,0,0,3,0,3,LOUD
297,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,2 Fracture,tuyz,Omen,0.79 0.95 0.61,132 173 88,...,0,0,0,0,0,0,0,0,0,LOUD

cauanzin

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
112,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,cauanzin,Breach,0.90 0.82 0.95,177 186 172,...,3,1,2,2,1,1,1,0,1,LOUD
121,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,2 Ascent,cauanzin,Sova,0.75 0.66 0.91,183 159 235,...,1,1,0,2,1,1,-1,0,-1,LOUD
289,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,1 Lotus,cauanzin,Skye,0.66 0.48 0.77,146 80 186,...,2,0,2,1,1,0,1,-1,2,LOUD
298,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,2 Fracture,cauanzin,Breach,0.76 0.73 0.79,175 151 203,...,1,0,1,1,0,1,0,0,0,LOUD

Less

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
111,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,Less,Viper,0.92 0.63 1.11,164 63 232,...,1,0,1,2,0,2,-1,0,-1,LOUD
123,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,2 Ascent,Less,Killjoy,0.62 0.80 0.26,157 214 45,...,0,0,0,4,2,2,-4,-2,-2,LOUD
288,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,1 Lotus,Less,Killjoy,0.73 0.54 0.85,150 103 179,...,1,0,1,2,0,2,-1,0,-1,LOUD
295,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,2 Fracture,Less,Viper,1.37 1.15 1.62,327 252 410,...,1,0,1,1,0,1,0,0,0,LOUD

saadhak

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
114,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,saadhak,Kayo,0.58 0.66 0.53,111 117 108,...,1,1,0,4,2,2,-3,-1,-2,LOUD
124,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,2 Ascent,saadhak,Kayo,0.52 0.61 0.32,133 155 90,...,0,0,0,1,1,0,-1,-1,0,LOUD
286,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,1 Lotus,saadhak,Viper,0.81 0.50 0.99,148 109 172,...,2,1,1,3,2,1,-1,-1,0,LOUD
299,2023-06-17 23:00:00,EDward Gaming LOUD,EDward Gaming,2:0,BO3,2 Fracture,saadhak,Kayo,0.66 0.83 0.48,128 134 122,...,1,1,0,2,1,1,-1,0,-1,LOUD

jawgemo

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
116,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,jawgemo,Raze,1.34 1.11 1.69,286 242 354,...,3,3,0,5,3,2,-2,0,-2,Evil Geniuses
125,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,2 Ascent,jawgemo,Omen,1.76 2.16 1.56,300 343 279,...,3,1,2,0,0,0,3,1,2,Evil Geniuses
179,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,jawgemo,Raze,1.01 1.00 1.05,200 206 178,...,2,2,0,5,3,2,-3,-1,-2,Evil Geniuses
186,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,2 Haven,jawgemo,Astra,1.25 1.63 0.93,182 262 117,...,0,0,0,0,0,0,0,0,0,Evil Geniuses
205,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,1 Lotus,jawgemo,Omen,0.76 0.25 0.92,195 176 203,...,1,1,0,3,1,2,-2,0,-2,Evil Geniuses
216,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,2 Fracture,jawgemo,Raze,1.09 0.80 1.33,252 245 259,...,6,3,3,5,3,2,1,0,1,Evil Geniuses
228,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,3 Split,jawgemo,Raze,0.79 0.82 0.76,178 191 166,...,2,1,1,5,4,1,-3,-3,0,Evil Geniuses
249,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,1 Lotus,jawgemo,Omen,0.58 0.27 0.82,119 114 123,...,2,1,1,1,1,0,1,0,1,Evil Geniuses
257,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,2 Split,jawgemo,Raze,1.12 1.31 0.94,255 321 191,...,5,4,1,5,4,1,0,0,0,Evil Geniuses
269,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,3 Bind,jawgemo,Raze,0.45 0.45 0.45,144 108 181,...,2,1,1,4,3,1,-2,-2,0,Evil Geniuses
434,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,1 Fracture,jawgemo,Raze,1.09 0.47 1.51,203 101 273,...,5,1,4,4,3,1,1,-2,3,Evil Geniuses
442,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,2 Lotus,jawgemo,Omen,0.98 1.22 0.74,166 185 148,...,1,0,1,1,0,1,0,0,0,Evil Geniuses
452,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,3 Split,jawgemo,Raze,0.99 0.71 1.25,221 218 224,...,6,3,3,3,2,1,3,1,2,Evil Geniuses
463,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,4 Pearl,jawgemo,Harbor,1.22 1.48 1.06,251 183 292,...,2,0,2,2,0,2,0,0,0,Evil Geniuses
472,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,jawgemo,Omen,1.17 1.48 0.77,198 273 99,...,1,1,0,4,0,4,-3,1,-4,Evil Geniuses

C0M

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
115,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,C0M,Sova,1.53 1.53 1.51,235 254 209,...,1,0,1,0,0,0,1,0,1,Evil Geniuses
127,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,2 Ascent,C0M,Sova,1.30 1.70 1.11,172 164 176,...,0,0,0,2,1,1,-2,-1,-1,Evil Geniuses
176,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,C0M,Sova,1.49 1.56 1.21,282 284 280,...,2,2,0,1,1,0,1,1,0,Evil Geniuses
187,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,2 Haven,C0M,Sova,1.06 0.64 1.41,197 133 251,...,2,1,1,3,3,0,-1,-2,1,Evil Geniuses
208,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,1 Lotus,C0M,Breach,0.49 0.43 0.51,93 113 86,...,0,0,0,1,0,1,-1,0,-1,Evil Geniuses
217,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,2 Fracture,C0M,Sova,0.96 0.83 1.08,133 121 144,...,0,0,0,1,1,0,-1,-1,0,Evil Geniuses
227,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,3 Split,C0M,Viper,0.98 1.16 0.80,181 236 126,...,1,1,0,4,1,3,-3,0,-3,Evil Geniuses
247,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,1 Lotus,C0M,Viper,0.71 0.49 0.88,150 126 170,...,2,1,1,3,3,0,-1,-2,1,Evil Geniuses
259,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,2 Split,C0M,Viper,0.47 0.30 0.64,113 89 137,...,2,0,2,2,1,1,0,-1,1,Evil Geniuses
265,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,3 Bind,C0M,Brimstone,1.11 1.22 1.00,176 136 217,...,0,0,0,2,0,2,-2,0,-2,Evil Geniuses
432,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,1 Fracture,C0M,Sova,1.20 1.18 1.20,209 259 177,...,2,0,2,2,1,1,0,-1,1,Evil Geniuses
443,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,2 Lotus,C0M,Viper,0.91 1.12 0.70,229 295 164,...,2,1,1,1,0,1,1,1,0,Evil Geniuses
450,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,3 Split,C0M,Viper,1.05 0.55 1.50,201 129 268,...,2,0,2,0,0,0,2,0,2,Evil Geniuses
461,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,4 Pearl,C0M,Viper,1.39 1.58 1.28,237 256 226,...,3,3,0,0,0,0,3,3,0,Evil Geniuses
473,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,C0M,Sova,1.15 1.11 1.20,185 232 124,...,2,2,0,1,1,0,1,1,0,Evil Geniuses

Demon1

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
117,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,Demon1,Brimstone,1.22 1.32 1.07,253 249 261,...,2,0,2,3,2,1,-1,-2,1,Evil Geniuses
126,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,2 Ascent,Demon1,Jett,1.37 1.41 1.35,231 254 220,...,3,1,2,3,1,2,0,0,0,Evil Geniuses
178,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,Demon1,Brimstone,1.19 1.22 1.05,170 160 214,...,1,0,1,0,0,0,1,0,1,Evil Geniuses
189,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,2 Haven,Demon1,Jett,0.69 0.73 0.65,157 226 100,...,2,0,2,3,2,1,-1,-2,1,Evil Geniuses
209,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,1 Lotus,Demon1,Jett,0.45 0.03 0.61,134 20 173,...,2,0,2,4,2,2,-2,-2,0,Evil Geniuses
218,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,2 Fracture,Demon1,Brimstone,0.96 0.99 0.94,158 195 128,...,1,1,0,3,0,3,-2,1,-3,Evil Geniuses
226,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,3 Split,Demon1,Jett,1.00 0.78 1.23,217 197 237,...,1,0,1,1,0,1,0,0,0,Evil Geniuses
248,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,1 Lotus,Demon1,Jett,0.69 0.53 0.82,139 146 135,...,2,0,2,2,1,1,0,-1,1,Evil Geniuses
256,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,2 Split,Demon1,Jett,1.19 0.91 1.47,224 199 250,...,4,2,2,0,0,0,4,2,2,Evil Geniuses
267,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,3 Bind,Demon1,Chamber,1.05 1.46 0.65,233 311 156,...,6,3,3,2,1,1,4,2,2,Evil Geniuses
430,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,1 Fracture,Demon1,Brimstone,1.37 1.28 1.43,227 235 223,...,1,1,0,0,0,0,1,1,0,Evil Geniuses
441,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,2 Lotus,Demon1,Jett,1.00 0.86 1.13,195 173 217,...,3,0,3,4,2,2,-1,-2,1,Evil Geniuses
451,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,3 Split,Demon1,Jett,1.02 0.59 1.42,223 131 310,...,3,1,2,1,1,0,2,0,2,Evil Geniuses
462,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,4 Pearl,Demon1,Jett,1.27 1.55 1.11,215 261 189,...,4,1,3,1,0,1,3,1,2,Evil Geniuses
470,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,Demon1,Jett,1.64 1.54 1.77,353 289 440,...,5,3,2,2,1,1,3,2,1,Evil Geniuses

Ethan

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
118,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,Ethan,Breach,1.10 1.23 0.91,184 214 141,...,0,0,0,1,1,0,-1,-1,0,Evil Geniuses
128,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,2 Ascent,Ethan,Kayo,1.21 1.22 1.20,315 395 276,...,3,0,3,0,0,0,3,0,3,Evil Geniuses
177,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,Ethan,Breach,1.48 1.65 0.79,170 180 133,...,0,0,0,0,0,0,0,0,0,Evil Geniuses
188,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,2 Haven,Ethan,Breach,1.05 1.00 1.10,176 199 158,...,3,1,2,2,1,1,1,0,1,Evil Geniuses
207,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,1 Lotus,Ethan,Skye,0.50 0.61 0.46,86 107 79,...,0,0,0,0,0,0,0,0,0,Evil Geniuses
219,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,2 Fracture,Ethan,Breach,0.75 0.42 1.03,167 119 208,...,0,0,0,0,0,0,0,0,0,Evil Geniuses
225,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,3 Split,Ethan,Skye,1.13 1.06 1.20,236 238 234,...,3,2,1,2,2,0,1,0,1,Evil Geniuses
245,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,1 Lotus,Ethan,Skye,1.08 0.99 1.14,211 225 202,...,2,0,2,1,0,1,1,0,1,Evil Geniuses
255,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,2 Split,Ethan,Skye,1.23 1.08 1.37,211 208 215,...,1,0,1,2,0,2,-1,0,-1,Evil Geniuses
266,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,3 Bind,Ethan,Skye,1.08 1.24 0.92,157 236 80,...,0,0,0,1,0,1,-1,0,-1,Evil Geniuses
431,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,1 Fracture,Ethan,Breach,1.36 1.08 1.55,198 187 207,...,0,0,0,0,0,0,0,0,0,Evil Geniuses
440,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,2 Lotus,Ethan,Skye,1.06 1.03 1.09,202 197 208,...,0,0,0,0,0,0,0,0,0,Evil Geniuses
454,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,3 Split,Ethan,Skye,0.55 0.36 0.72,113 88 136,...,1,0,1,1,1,0,0,-1,1,Evil Geniuses
464,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,4 Pearl,Ethan,Skye,1.03 1.21 0.92,130 147 120,...,2,1,1,1,1,0,1,0,1,Evil Geniuses
471,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,Ethan,Kayo,1.31 1.21 1.44,216 199 238,...,2,1,1,1,1,0,1,0,1,Evil Geniuses

Boostio

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
119,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,Boostio,Killjoy,0.74 0.66 0.86,150 189 93,...,4,2,2,1,1,0,3,1,2,Evil Geniuses
129,2023-06-15 23:00:00,LOUD Evil Geniuses,Evil Geniuses,2:0,BO3,2 Ascent,Boostio,Killjoy,0.73 0.51 0.84,161 123 180,...,3,1,2,1,1,0,2,0,2,Evil Geniuses
175,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,1 Fracture,Boostio,Killjoy,1.55 1.50 1.76,347 350 341,...,4,4,0,0,0,0,4,4,0,Evil Geniuses
185,2023-06-18 23:00:00,Team Liquid Evil Geniuses,Evil Geniuses,2:0,BO3,2 Haven,Boostio,Killjoy,1.28 0.83 1.67,287 186 372,...,5,1,4,2,1,1,3,0,3,Evil Geniuses
206,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,1 Lotus,Boostio,Killjoy,0.67 0.17 0.83,158 44 196,...,0,0,0,5,0,5,-5,0,-5,Evil Geniuses
215,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,2 Fracture,Boostio,Killjoy,1.37 0.74 1.90,264 167 346,...,5,1,4,1,1,0,4,0,4,Evil Geniuses
229,2023-06-20 23:00:00,FNATIC Evil Geniuses,FNATIC,2:1,BO3,3 Split,Boostio,Astra,0.70 0.80 0.59,169 171 168,...,2,1,1,3,0,3,-1,1,-2,Evil Geniuses
246,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,1 Lotus,Boostio,Killjoy,1.05 0.55 1.43,274 132 382,...,4,1,3,2,1,1,2,0,2,Evil Geniuses
258,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,2 Split,Boostio,Astra,0.92 0.41 1.44,145 64 227,...,2,0,2,1,1,0,1,-1,2,Evil Geniuses
268,2023-06-25 00:30:00,FNATIC Evil Geniuses,FNATIC,3:0,BO5,3 Bind,Boostio,Reyna,0.74 0.65 0.82,149 160 139,...,4,2,2,5,3,2,-1,-1,0,Evil Geniuses
433,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,1 Fracture,Boostio,Killjoy,1.09 0.55 1.44,241 163 294,...,4,1,3,2,1,1,2,0,2,Evil Geniuses
444,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,2 Lotus,Boostio,Killjoy,0.84 0.78 0.90,209 203 216,...,6,4,2,8,6,2,-2,-2,0,Evil Geniuses
453,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,3 Split,Boostio,Astra,0.86 0.67 1.04,211 200 222,...,4,2,2,2,1,1,2,1,1,Evil Geniuses
460,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,4 Pearl,Boostio,Killjoy,1.48 1.01 1.76,283 232 313,...,2,0,2,2,1,1,0,-1,1,Evil Geniuses
474,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,Boostio,Killjoy,0.58 0.69 0.45,151 206 79,...,1,1,0,2,1,1,-1,0,-1,Evil Geniuses

In [27]:
desired_rows = df[df.apply(lambda row: row.astype(str).str.contains('f0rsakeN').any(), axis=1) & ~df.apply(lambda row: row.astype(str).str.contains('Deadlock').any(), axis=1)]
desired_rows

,Date,VS,Winner,Scoreline,Series Type,Map,Player,Agent,R,ACS,...,FK_all,FK_attack,FK_defend,FD_all,FD_attack,FD_defend,FKFD +/-_all,FKFD +/-_attack,FKFD +/-_defend,Team
12,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,1 Split,f0rsakeN,Jett,1.26 1.77 0.70,248 348 140,...,5,3,2,3,2,1,2,1,1,Paper Rex
24,2023-06-17 01:30:00,Paper Rex DRX,Paper Rex,2:0,BO3,2 Bind,f0rsakeN,Harbor,0.82 0.81 0.83,124 142 109,...,1,0,1,2,0,2,-1,0,-1,Paper Rex
142,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,1 Lotus,f0rsakeN,Cypher,0.80 0.58 1.24,149 161 125,...,0,0,0,2,2,0,-2,-2,0,Paper Rex
150,2023-06-19 01:15:00,Paper Rex FNATIC,FNATIC,2:0,BO3,2 Bind,f0rsakeN,Harbor,1.15 1.23 1.09,258 238 272,...,4,1,3,1,0,1,3,1,2,Paper Rex
353,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,1 Fracture,f0rsakeN,Neon,0.89 0.82 0.97,223 232 215,...,5,3,2,3,2,1,2,1,1,Paper Rex
361,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,2 Split,f0rsakeN,Jett,0.86 0.88 0.83,228 253 208,...,6,2,4,4,2,2,2,0,2,Paper Rex
374,2023-06-20 02:45:00,Paper Rex EDward Gaming,Paper Rex,2:1,BO3,3 Lotus,f0rsakeN,Cypher,0.93 0.78 1.05,178 141 206,...,1,0,1,3,3,0,-2,-3,1,Paper Rex
398,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,1 Pearl,f0rsakeN,Jett,0.97 0.70 1.23,235 215 256,...,8,5,3,4,3,1,4,2,2,Paper Rex
406,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,2 Lotus,f0rsakeN,Cypher,0.77 0.78 0.76,196 159 218,...,5,2,3,5,3,2,0,-1,1,Paper Rex
415,2023-06-21 02:25:00,NRG Esports Paper Rex,Paper Rex,2:1,BO3,3 Bind,f0rsakeN,Harbor,1.50 1.57 1.42,287 251 325,...,3,2,1,3,2,1,0,0,0,Paper Rex
436,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,1 Fracture,f0rsakeN,Neon,0.89 0.60 1.32,211 189 244,...,3,1,2,6,4,2,-3,-3,0,Paper Rex
448,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,2 Lotus,f0rsakeN,Cypher,0.91 1.08 0.74,187 213 163,...,3,2,1,2,0,2,1,2,-1,Paper Rex
457,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,3 Split,f0rsakeN,Jett,1.10 0.48 1.78,228 134 332,...,3,1,2,4,4,0,-1,-3,2,Paper Rex
469,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,4 Pearl,f0rsakeN,Jett,0.66 0.46 1.01,212 181 265,...,4,2,2,5,3,2,-1,-1,0,Paper Rex
476,2023-06-23 23:00:00,Evil Geniuses Paper Rex,Evil Geniuses,3:2,BO5,5 Ascent,f0rsakeN,Jett,0.97 1.26 0.76,262 318 221,...,4,3,1,4,1,3,0,2,-2,Paper Rex